Update arcasHLA

diff --git a/arcasHLA b/arcasHLA
--- a/arcasHLA
+++ b/arcasHLA
@@ -1,52 +1,98 @@
 #!/bin/bash
+#-----------------------------------------------------------------------------
+#   arcasHLA: high resolution HLA typing from RNA seq
+#-----------------------------------------------------------------------------
+#
+#   Authors:    Rose Orenbuch, Ioan Filip, Itsik Pe'er
+#   Date:       November 2018
+#   Version:    1.0
+#   License:    GNU
+#
+#-----------------------------------------------------------------------------
+#   
+#   arcasHLA types high resolution HLA alleles from BAM.
+#
+#-----------------------------------------------------------------------------
+#   Requirements
+#-----------------------------------------------------------------------------
 
-#This file is part of arcasHLA.
-#
-#    arcasHLA is free software: you can redistribute it and/or modify
-#    it under the terms of the GNU General Public License as published by
-#    the Free Software Foundation, either version 3 of the License, or
-#    (at your option) any later version.
-#
-#    arcasHLA is distributed in the hope that it will be useful,
-#    but WITHOUT ANY WARRANTY; without even the implied warranty of
-#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-#    GNU General Public License for more details.
-#
-#    You should have received a copy of the GNU General Public License
-#    along with arcasHLA.  If not, see <https://www.gnu.org/licenses/>.
+missing=$false
+if [ ! -x "$(command -v kallisto pseudo)" ]; then
+    echo "Missing dependency: Kallisto v0.44.0"
+    missing=$true
+fi
 
+if [ ! -x "$(command -v samtools)" ]; then
+    echo "Missing dependency: Samtools"
+    missing=$true
+fi
+
+if [ ! -x "$(command -v bedtools)" ]; then
+    echo "Missing dependency: bedtools"
+    missing=$true
+fi
+
+if [ ! -x "$(command -v pigz)" ]; then
+    echo "Missing dependency: pigz"
+    missing=$true
+fi
+
+if [ ! -x "$(command -v python3 -c "import numpy")" ]; then
+    echo "Missing dependency: python3 module NumPy"
+    missing=$true
+fi
+
+if [ ! -x "$(command -v python3 -c "import pandas")" ]; then
+    echo "Missing dependency: python3 module pandas"
+    missing=$true
+fi
+
+if [ ! -x "$(command -v python3 -c "import Bio")" ]; then
+    echo "Missing dependency: python3 module Biopython"
+    missing=$true
+fi
+
+if [ $missing == $true ]; then
+    exit 1
+fi
+
+#-----------------------------------------------------------------------------
+#   Tools
 #-----------------------------------------------------------------------------
 
 if [ "$1" == "extract" ]; then
 
-    python ./scripts/extract.py ${@:2}
+    python3 ./scripts/extract.py ${@:2}
 
 elif [ "$1" == "genotype" ]; then
 
-    python ./scripts/genotype.py ${@:2}
+    python3 ./scripts/genotype.py ${@:2}
 
-elif [ "$1" == "table" ]; then
+elif [ "$1" == "merge" ]; then
 
-    python ./scripts/table.py ${@:2}
+    python3 ./scripts/merge.py ${@:2}
 
 elif [ "$1" == "reference" ]; then
 
-    python ./scripts/build_reference.py ${@:2}
+    python3 ./scripts/reference.py ${@:2}
 
 elif [ "$1" == "partial" ]; then
 
-    python ./scripts/partial.py ${@:2}
+    python3 ./scripts/partial.py ${@:2}
+    
+#-----------------------------------------------------------------------------
+#   Usage
+#-----------------------------------------------------------------------------
 
 else
-    echo
     echo "Usage: arcasHLA <command> [options]"
     echo
     echo "    extract        extracts chromosome 6 reads from bam"
     echo "    genotype       types HLA genes from extracted reads"
-    echo "    partial        types partial HLA alleles from extracted reads"
-    echo "    table          processes results into a tab-separated table"
+    echo "    partial        types partial HLA genes from extracted reads"
+    echo "    merge          processes results into a tab-separated table"
     echo "    reference      check or update HLA reference"
-    echo
+    echo 
     echo "Note: run any command with --help to view required fields, options"
     echo
 fi
